version: "1"

services:
  - type: web
    name: strathub-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npx tsc
    startCommand: node dist/app.js
    region: frankfurt
    plan: free
    envVars:
      - key: NODE_ENV
        value: staging
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://strathub-frontend.onrender.com

  - type: static
    name: strathub-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    plan: free
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    envVars:
      - key: VITE_API_URL
        value: https://strathub-backend.onrender.com
